### ISSUE TITLE
I'm not a contributor

### ISSUE THREAD

**Issue by xeryus-velasco** [JamesGaier/OpenGl#3]
In all seriousness, I would like to work with you on this project. @Nicholas-Baron said I can help.

- [x] Make me a member
- [x] Die instantly

**Comment by Nicholas-Baron** [comment]
Your comment has been processed. Please wait for further action.

**Comment by JamesGaier** [comment]
you can join if nicks cool with it, just know OpenGL is hell, but somewhat rewarding when you get it.
