### ISSUE TITLE
how did you upload the dependancies!?!?!

### ISSUE THREAD

**Issue by JamesGaier** [JamesGaier/OpenGl#4]
I tried uploading the dependencies earlier and GitHub told me that there were over a hundred files so I couldn't.

**Comment by Nicholas-Baron** [comment]
.gitignore + clean out the stuff we do not need

**Comment by JamesGaier** [comment]
okay

**Comment by JamesGaier** [comment]
i can update main file to where im at if you like

**Comment by Nicholas-Baron** [comment]
Put it in your branch
